import type {
  TenantCustomer,
  BodRequestItem,
  SlaComplianceRecord,
  PredictiveWarning,
  MaintenanceTicketItem,
  InvoiceStatement,
} from "@/types/lifecycle";

export const INITIAL_TENANTS: TenantCustomer[] = [
  {
    id: "TNT-001",
    name: "Google Global Cache & Peering",
    asn: 15169,
    customerType: "Hyperscaler",
    contactEmail: "peering-noc@google.com",
    rackLocation: "MMR-A / R08-12",
    activeCircuitsCount: 12,
    contractTier: "Gold",
    monthlyBaseCommit: 14400,
    status: "Active",
  },
  {
    id: "TNT-002",
    name: "Cloudflare Edge Network",
    asn: 13335,
    customerType: "CDN",
    contactEmail: "ops@cloudflare.com",
    rackLocation: "MMR-B / R21-04",
    activeCircuitsCount: 8,
    contractTier: "Gold",
    monthlyBaseCommit: 9600,
    status: "Active",
  },
  {
    id: "TNT-003",
    name: "PT Bank Mandiri (FSI Primary)",
    asn: 4761,
    customerType: "FSI",
    contactEmail: "netops.sec@bankmandiri.co.id",
    rackLocation: "MMR-A / R03-02",
    activeCircuitsCount: 4,
    contractTier: "Platinum",
    monthlyBaseCommit: 8800,
    status: "Active",
  },
  {
    id: "TNT-004",
    name: "Microsoft Azure Peering",
    asn: 8075,
    customerType: "Hyperscaler",
    contactEmail: "ms-peering@microsoft.com",
    rackLocation: "MMR-B / R14-08",
    activeCircuitsCount: 16,
    contractTier: "Gold",
    monthlyBaseCommit: 19200,
    status: "Active",
  },
  {
    id: "TNT-005",
    name: "Akamai Technologies Edge",
    asn: 20940,
    customerType: "CDN",
    contactEmail: "akamai-noc@akamai.com",
    rackLocation: "MMR-A / R11-06",
    activeCircuitsCount: 6,
    contractTier: "Gold",
    monthlyBaseCommit: 7200,
    status: "Active",
  },
  {
    id: "TNT-006",
    name: "Telkom Indonesia Transit",
    asn: 7713,
    customerType: "Enterprise",
    contactEmail: "noc@telkom.co.id",
    rackLocation: "MMR-B / R22-10",
    activeCircuitsCount: 10,
    contractTier: "Silver",
    monthlyBaseCommit: 6500,
    status: "Active",
  },
];

export const INITIAL_BOD_REQUESTS: BodRequestItem[] = [
  {
    id: "BOD-40217",
    tenantId: "TNT-001",
    tenantName: "Google Global Cache",
    route: "MMR-A/R08 ──▶ Fabric-01",
    sourcePanel: "XSOS-576D-1",
    sourcePort: 24,
    targetPanel: "XSOS-576D-2",
    targetPort: 120,
    capacity: "100G",
    slaTier: "Gold",
    duration: "Recurring",
    stage: 3,
    submittedAt: "14:02:11",
    insertionLossDb: 0.44,
    returnLossDb: -66.5,
    estSwitchingTimeSec: 42,
    monthlyCost: 1200,
    autoApproved: true,
  },
  {
    id: "BOD-40216",
    tenantId: "TNT-002",
    tenantName: "Cloudflare Edge",
    route: "MMR-B/R21 ──▶ Fabric-02",
    sourcePanel: "XSOS-576D-2",
    sourcePort: 48,
    targetPanel: "XSOS-576D-3",
    targetPort: 210,
    capacity: "400G",
    slaTier: "Platinum",
    duration: "Temporary Burst (24h)",
    stage: 1,
    submittedAt: "13:47:30",
    insertionLossDb: 0.46,
    returnLossDb: -67.1,
    estSwitchingTimeSec: 44,
    monthlyCost: 3500,
    autoApproved: true,
  },
  {
    id: "BOD-40215",
    tenantId: "TNT-003",
    tenantName: "Bank Mandiri FSI",
    route: "MMR-A/R03 ──▶ Fabric-01",
    sourcePanel: "XSOS-576D-1",
    sourcePort: 12,
    targetPanel: "XSOS-576D-2",
    targetPort: 88,
    capacity: "100G",
    slaTier: "Silver",
    duration: "Recurring",
    stage: 0,
    submittedAt: "13:31:05",
    insertionLossDb: 0.42,
    returnLossDb: -68.0,
    estSwitchingTimeSec: 39,
    monthlyCost: 1200,
    autoApproved: true,
  },
  {
    id: "BOD-40209",
    tenantId: "TNT-004",
    tenantName: "Microsoft Azure",
    route: "MMR-B/R14 ──▶ Fabric-02",
    sourcePanel: "XSOS-576D-2",
    sourcePort: 96,
    targetPanel: "XSOS-576D-4",
    targetPort: 160,
    capacity: "10G",
    slaTier: "Gold",
    duration: "Event (72h)",
    stage: 3,
    submittedAt: "11:58:40",
    insertionLossDb: 0.38,
    returnLossDb: -69.2,
    estSwitchingTimeSec: 36,
    monthlyCost: 300,
    autoApproved: true,
  },
  {
    id: "BOD-40204",
    tenantId: "TNT-005",
    tenantName: "Akamai Technologies",
    route: "MMR-A/R11 ──▶ Fabric-01",
    sourcePanel: "XSOS-576D-1",
    sourcePort: 60,
    targetPanel: "XSOS-576D-2",
    targetPort: 180,
    capacity: "100G",
    slaTier: "Bronze",
    duration: "Recurring",
    stage: 3,
    submittedAt: "09:12:15",
    insertionLossDb: 0.45,
    returnLossDb: -66.0,
    estSwitchingTimeSec: 41,
    monthlyCost: 1200,
    autoApproved: true,
  },
];

export const INITIAL_SLA_COMPLIANCE: SlaComplianceRecord[] = [
  {
    customerType: "Hyperscaler",
    slaTier: "Gold",
    uptimeTargetPct: 99.99,
    actualUptimePct: 99.995,
    latencyTargetMs: 2.0,
    actualLatencyMs: 1.4,
    status: "Good",
  },
  {
    customerType: "CDN",
    slaTier: "Gold",
    uptimeTargetPct: 99.99,
    actualUptimePct: 99.992,
    latencyTargetMs: 3.0,
    actualLatencyMs: 2.6,
    status: "Good",
  },
  {
    customerType: "FSI (Financial Services)",
    slaTier: "Platinum",
    uptimeTargetPct: 99.999,
    actualUptimePct: 99.997,
    latencyTargetMs: 1.0,
    actualLatencyMs: 1.2,
    status: "Watch",
  },
  {
    customerType: "Enterprise",
    slaTier: "Silver",
    uptimeTargetPct: 99.95,
    actualUptimePct: 99.968,
    latencyTargetMs: 5.0,
    actualLatencyMs: 3.1,
    status: "Good",
  },
];

export const INITIAL_PREDICTIVE_WARNINGS: PredictiveWarning[] = [
  {
    id: "PRED-01",
    unit: "XSOS-576D-MDF2",
    message: "Elevated packet retry rate on Module 14 fiber tray",
    riskLevel: "Low",
    forecastWindowDays: 30,
    category: "Optical",
  },
  {
    id: "PRED-02",
    unit: "XSOS-576D-MMRB-02",
    message: "Thermal drift detected near Robotic Stepper Unit B",
    riskLevel: "Low",
    forecastWindowDays: 45,
    category: "Thermal",
  },
  {
    id: "PRED-03",
    unit: "SDN Core Controller",
    message: "No anomalies detected in log pattern analysis",
    riskLevel: "Low",
    forecastWindowDays: 60,
    category: "Control Plane",
  },
];

export const INITIAL_MAINTENANCE_TICKETS: MaintenanceTicketItem[] = [
  {
    id: "TCK-8842",
    category: "Optical LOS",
    title: "Optical LOS — Port 214, XSOS-576D-MMRB-02",
    source: "DC Facilities",
    location: "Zone B (5th Floor)",
    status: "Scheduled",
    severity: "Critical",
    window: "Today 22:00 – 00:00",
  },
  {
    id: "TCK-8839",
    category: "NetConf Controller",
    title: "SDN Controller API response latency spike (842ms)",
    source: "Software Ops Team",
    location: "Remote Control Plane",
    status: "In Progress",
    severity: "Warning",
    window: "Ongoing Active Investigation",
  },
  {
    id: "TCK-8831",
    category: "Preventive Swap",
    title: "Fiber tray alignment inspection — MDF-2",
    source: "DC Facilities",
    location: "Ground Floor Telecom Room",
    status: "Resolved",
    severity: "Info",
    window: "Closed 11:40 SGT",
  },
  {
    id: "TCK-8827",
    category: "Preventive Swap",
    title: "Module 14 preventive cassette swap — XSOS-576D-MDF2",
    source: "Field Engineering",
    location: "Ground Floor MDF-2",
    status: "Scheduled",
    severity: "Info",
    window: "Sat 02:00 – 04:00 SGT",
  },
];

export const INITIAL_INVOICES: InvoiceStatement[] = [
  {
    invoiceNo: "INV-2026-0901",
    tenantId: "TNT-001",
    tenantName: "Google Global Cache & Peering",
    asn: 15169,
    billingPeriod: "September 2026",
    basePortFee: 14400,
    bodBurstUsageHours: 72,
    bodBurstRatePerHour: 15,
    bodBurstTotal: 1080,
    slaOutageDowntimeMin: 0,
    slaPenaltyCredit: 0,
    subtotal: 15480,
    taxAmount: 1625.4,
    totalDue: 17105.4,
    status: "Issued",
    dueDate: "2026-10-15",
  },
  {
    invoiceNo: "INV-2026-0902",
    tenantId: "TNT-002",
    tenantName: "Cloudflare Edge Network",
    asn: 13335,
    billingPeriod: "September 2026",
    basePortFee: 9600,
    bodBurstUsageHours: 120,
    bodBurstRatePerHour: 25,
    bodBurstTotal: 3000,
    slaOutageDowntimeMin: 12,
    slaPenaltyCredit: 450, // Potongan penalti SLA
    subtotal: 12150,
    taxAmount: 1275.75,
    totalDue: 13425.75,
    status: "Issued",
    dueDate: "2026-10-15",
  },
  {
    invoiceNo: "INV-2026-0903",
    tenantId: "TNT-003",
    tenantName: "PT Bank Mandiri (FSI Primary)",
    asn: 4761,
    billingPeriod: "September 2026",
    basePortFee: 8800,
    bodBurstUsageHours: 0,
    bodBurstRatePerHour: 20,
    bodBurstTotal: 0,
    slaOutageDowntimeMin: 4,
    slaPenaltyCredit: 320,
    subtotal: 8480,
    taxAmount: 890.4,
    totalDue: 9370.4,
    status: "Paid",
    dueDate: "2026-10-05",
  },
];
